runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
