on:
  release:
    types:
      - created

jobs:
  ros:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - name: ros
        run: |
          num_tags=`git tag --sort=-version:refname | wc -l`
          if [[ $num_tags > 1 ]]; then
             latest_tag=`git tag --sort=-version:refname | head -n1`
             previous_tag=`git tag --sort=-version:refname | head -n2 | tail -n1`
             if [[ ! `git diff "$latest_tag" "$previous_tag" ros` ]]; then
                exit 0
             fi
          fi

          cd ros
          docker build -f ./dockerfiles/ubuntu2004.dockerfile -t ros .
          docker tag ros:latest ${{ secrets.DOCKER_USERNAME }}/ros:noetic-ubuntu20.04
          docker push ${{ secrets.DOCKER_USERNAME }}/ros:noetic-ubuntu20.04
          docker image prune -f

  ros2:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - name: ros2
        run: |
          num_tags=`git tag --sort=-version:refname | wc -l`
          if [[ $num_tags > 1 ]]; then
             latest_tag=`git tag --sort=-version:refname | head -n1`
             previous_tag=`git tag --sort=-version:refname | head -n2 | tail -n1`
             if [[ ! `git diff "$latest_tag" "$previous_tag" ros2` ]]; then
                exit 0
             fi
          fi

          cd ros2
          docker build -f ./dockerfiles/ubuntu2004.dockerfile -t ros2 .
          docker tag ros2:latest ${{ secrets.DOCKER_USERNAME }}/ros2:galactic-ubuntu20.04
          docker push ${{ secrets.DOCKER_USERNAME }}/ros2:galactic-ubuntu20.04
          docker image prune -f

  torch_cpp:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - name: torch_cpp
        run: |
          num_tags=`git tag --sort=-version:refname | wc -l`
          if [[ $num_tags > 1 ]]; then
             latest_tag=`git tag --sort=-version:refname | head -n1`
             previous_tag=`git tag --sort=-version:refname | head -n2 | tail -n1`
             if [[ ! `git diff "$latest_tag" "$previous_tag" torch_cpp` ]]; then
                exit 0
             fi
          fi

          cd torch_cpp
          docker build -f ./dockerfiles/ubuntu2004.dockerfile -t torch_cpp .
          docker tag torch_cpp:latest ${{ secrets.DOCKER_USERNAME }}/torch_cpp:1.12.1-ubuntu20.04
          docker push ${{ secrets.DOCKER_USERNAME }}/torch_cpp:1.12.1-ubuntu20.04
          docker image prune -f

  onnx_runtime_cpp:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - name: onnx_runtime_cpp
        run: |
          num_tags=`git tag --sort=-version:refname | wc -l`
          if [[ $num_tags > 1 ]]; then
             latest_tag=`git tag --sort=-version:refname | head -n1`
             previous_tag=`git tag --sort=-version:refname | head -n2 | tail -n1`
             if [[ ! `git diff "$latest_tag" "$previous_tag" onnx_runtime_cpp` ]]; then
                exit 0
             fi
          fi

          cd onnx_runtime_cpp
          docker build -f ./dockerfiles/ubuntu2004.dockerfile -t onnx_runtime_cpp .
          docker tag onnx_runtime_cpp:latest ${{ secrets.DOCKER_USERNAME }}/onnx_runtime_cpp:v1.10.0-ubuntu20.04
          docker push ${{ secrets.DOCKER_USERNAME }}/onnx_runtime_cpp:v1.10.0-ubuntu20.04
          docker image prune -f
