name: Release

on:
  release:
    types:
      - created

jobs:
  ros:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - uses: ./.github/workflows/composite/release-on-changes
        with:
          directory_name: ros
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          tag_name: noetic-ubuntu20.04

  ros2:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - uses: ./.github/workflows/composite/release-on-changes
        with:
          directory_name: ros2
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          tag_name: galactic-ubuntu20.04

  torch_cpp:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - uses: ./.github/workflows/composite/release-on-changes
        with:
          directory_name: torch_cpp
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          tag_name: 1.12.1-ubuntu20.04

  onnx_runtime_cpp:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - uses: ./.github/workflows/composite/release-on-changes
        with:
          directory_name: onnx_runtime_cpp
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          tag_name: v1.14.1-ubuntu20.04

  open_dynamics_engine:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite/setup-docker-env-login
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}

      - uses: ./.github/workflows/composite/release-on-changes
        with:
          directory_name: open_dynamics_engine
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          tag_name: 0.16.4-ubuntu20.04
